version: '3'

services:
  mongo:
    image: mongo:6.0.7
    restart: always
    container_name: mongoContainer
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass1234
    ports:
      - 5000:27017
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongoExpressContainer
    restart: always
    ports:
      - 5001:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: sergio
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass1234
      ME_CONFIG_MONGODB_URL: mongodb://root:pass1234@mongo:27017/     #Conexion local entre contenedor
    networks:
      - mongo-network

  api:
    build: .
    image: sergioroger/apimongots:v1
    container_name: api
    environment:
      PORT: 4000
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: mybd
      MONGO_USER: root
      MONGO_PASS: pass1234
    ports:
      - 3000:4000
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
